const FETCH_INIT = 'FETCH_INIT';
const FETCH_PLANTS = 'FETCH_PLANTS';
const FETCH_FAIL = 'FETCH_FAIL';
const CHANGE_FILTER = 'CHANGE_FILTER';
const FETCH_CATEGORY = 'FETCH_CATEGORY';
const FETCH_PLANT = 'FETCH_PLANT';
const SELECT_PLANT = 'SELECT_PLANT';
const FETCH_INIT_PLANT = 'FETCH_INIT_PLANT';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_PLANT_ERROR = 'FETCH_PLANT_ERROR';

export {
  FETCH_INIT,
  FETCH_PLANTS,
  FETCH_FAIL,
  CHANGE_FILTER,
  FETCH_CATEGORY,
  FETCH_PLANT,
  SELECT_PLANT,
  FETCH_INIT_PLANT,
  FETCH_SUCCESS,
  FETCH_PLANT_ERROR,
};
