const FETCH_INIT = 'FETCH_INIT';
const FETCH_PLANTS = 'FETCH_PLANTS';
const FETCH_FAIL = 'FETCH_FAIL';
const CHANGE_FILTER = 'CHANGE_FILTER';
const FETCH_CATEGORY = 'FETCH_CATEGORY';

export {
  FETCH_INIT,
  FETCH_PLANTS,
  FETCH_FAIL,
  CHANGE_FILTER,
  FETCH_CATEGORY,
};
